-- Jalankan file ini manual di Supabase SQL Editor.
-- Prasyarat: lembaga.id bertipe bigint (sudah dikonfirmasi).

-- 1. Tabel kode registrasi — satu kode aktif per lembaga
create table public.kode_registrasi (
  id          bigint generated by default as identity primary key,
  lembaga_id  bigint not null references public.lembaga(id) on delete cascade,
  kode        text not null unique,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  constraint kode_registrasi_lembaga_id_key unique (lembaga_id)
);

alter table public.kode_registrasi enable row level security;
-- SENGAJA nol policy. RLS enabled + tanpa policy = default-deny total untuk
-- role `anon` & `authenticated`. Yang bisa baca/tulis tabel ini cuma:
--   a) service_role (BYPASSRLS) via admin.ts
--   b) function SECURITY DEFINER di bawah (jalan sebagai owner `postgres`)
-- Tabel ini TIDAK PERNAH diakses langsung dari client.

-- 2. Trigger: link auth.users baru -> profil_amil, baca kode dari signup metadata
create or replace function public.handle_new_amil_registration()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_kode text;
  v_lembaga_id bigint;
begin
  v_kode := upper(trim(new.raw_user_meta_data->>'kode_registrasi'));

  if v_kode is null or v_kode = '' then
    raise exception 'Kode registrasi wajib diisi.';
  end if;

  select lembaga_id into v_lembaga_id
  from public.kode_registrasi
  where kode = v_kode;

  if v_lembaga_id is null then
    raise exception 'Kode registrasi tidak valid atau sudah tidak berlaku.';
  end if;

  insert into public.profil_amil (id, lembaga_id)
  values (new.id, v_lembaga_id);

  return new;
end;
$$;

drop trigger if exists on_auth_user_created_link_amil on auth.users;
create trigger on_auth_user_created_link_amil
  after insert on auth.users
  for each row
  execute function public.handle_new_amil_registration();

-- 3. RPC atomik: bikin lembaga + kode registrasinya sekaligus (dipakai panel admin,
--    hindari state setengah-jadi kalau insert kedua gagal setelah insert pertama sukses)
create or replace function public.admin_create_lembaga_with_kode(
  p_nama text, p_alamat text, p_satuan_beras text, p_kode text
) returns table (lembaga_id bigint, kode text)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_lembaga_id bigint;
begin
  insert into public.lembaga (nama, alamat, satuan_beras)
  values (p_nama, p_alamat, p_satuan_beras)
  returning id into v_lembaga_id;

  insert into public.kode_registrasi (lembaga_id, kode)
  values (v_lembaga_id, p_kode);

  return query select v_lembaga_id, p_kode;
end;
$$;
