-- Jalankan file ini manual di Supabase SQL Editor.
-- Tabel anggota keluarga di bawah satu mustahik (kepala keluarga).
-- Murni pendataan dulu — belum dipakai untuk kalkulasi distribusi zakat apa pun.

create table public.anggota_keluarga_mustahik (
  id          bigint generated by default as identity primary key,
  mustahik_id bigint not null references public.mustahik(id) on delete cascade,
  nama        text not null,
  hubungan    text not null,
  lembaga_id  bigint references public.lembaga(id),
  created_at  timestamptz not null default now()
);

alter table public.anggota_keluarga_mustahik enable row level security;

-- PENTING: sesuaikan policy di bawah ini supaya PERSIS sama pola RLS yang
-- sudah dipakai di tabel `mustahik` (RLS aslinya tidak terlihat dari repo ini
-- karena tidak ada migration lama yang tersimpan). Contoh generik di bawah
-- ini cuma tebakan berdasarkan pola "amil hanya akses lembaga_id miliknya
-- sendiri" yang didokumentasikan di CLAUDE.md — cek dulu ke tabel `mustahik`
-- pakai Supabase Dashboard -> Authentication -> Policies, lalu samakan.
create policy "Amil akses anggota keluarga lembaga sendiri"
  on public.anggota_keluarga_mustahik
  for all
  using (
    lembaga_id in (
      select lembaga_id from public.profil_amil where id = auth.uid()
    )
  )
  with check (
    lembaga_id in (
      select lembaga_id from public.profil_amil where id = auth.uid()
    )
  );
