-- Jalankan file ini manual di Supabase SQL Editor.
-- (Menggantikan draft 0004 sebelumnya -- jangan jalankan draft lama kalau
-- sempat sudah dicoba, drop dulu tabelnya kalau perlu.)
--
-- Model: satu "sesi_distribusi" (batch/session) berisi banyak baris
-- "distribusi_zakat" (satu baris per mustahik). Sesi dibuat SEKALI SAJA
-- lewat function create_sesi_distribusi() -- header + semua baris masuk
-- dalam satu transaksi atomik (RPC), supaya gak ada sesi yang "nyangkut"
-- setengah jadi (header ada tapi baris mustahik-nya gagal, atau sebaliknya).
--
-- "Sisa yang tersedia" untuk kalkulasi SELALU dihitung live (total transaksi
-- masuk dikurangi SUM seluruh sesi_distribusi yang sudah pernah dibuat) --
-- bukan angka yang disimpan terpisah -- supaya nominal yang sudah tersalur
-- di sesi sebelumnya tidak pernah terhitung dua kali.

create table public.sesi_distribusi (
  id                bigint generated by default as identity primary key,
  jenis             text not null check (jenis in ('Zakat Mal', 'Zakat Fitrah')),
  total_uang        numeric not null default 0,
  total_beras       numeric not null default 0,
  jumlah_penerima   int not null default 0,
  amil_pencatat     text,
  lembaga_id        bigint references public.lembaga(id),
  tanggal           timestamptz not null default now()
);

create table public.distribusi_zakat (
  id             bigint generated by default as identity primary key,
  sesi_id        bigint not null references public.sesi_distribusi(id) on delete cascade,
  mustahik_id    bigint not null references public.mustahik(id) on delete cascade,
  jumlah_uang    numeric not null default 0,
  jumlah_beras   numeric not null default 0,
  lembaga_id     bigint references public.lembaga(id)
);

alter table public.sesi_distribusi enable row level security;
alter table public.distribusi_zakat enable row level security;

-- PENTING: sesuaikan kedua policy di bawah supaya PERSIS sama pola RLS yang
-- sudah dipakai di tabel `transaksi` (RLS aslinya tidak terlihat dari repo
-- ini). Cek dulu ke Supabase Dashboard -> Authentication -> Policies.
create policy "Amil akses sesi distribusi lembaga sendiri"
  on public.sesi_distribusi
  for all
  using (lembaga_id in (select lembaga_id from public.profil_amil where id = auth.uid()))
  with check (lembaga_id in (select lembaga_id from public.profil_amil where id = auth.uid()));

create policy "Amil akses baris distribusi lembaga sendiri"
  on public.distribusi_zakat
  for all
  using (lembaga_id in (select lembaga_id from public.profil_amil where id = auth.uid()))
  with check (lembaga_id in (select lembaga_id from public.profil_amil where id = auth.uid()));

-- RPC atomik: bikin 1 sesi + semua baris distribusinya sekaligus.
-- SECURITY INVOKER (default) -- jalan pakai hak akses amil yang manggil,
-- jadi tetap tunduk RLS di atas (bukan bypass kayak RPC panel-zakat).
create or replace function public.create_sesi_distribusi(
  p_jenis text,
  p_total_uang numeric,
  p_total_beras numeric,
  p_lembaga_id bigint,
  p_amil_pencatat text,
  p_items jsonb -- array of { mustahik_id, jumlah_uang, jumlah_beras }
) returns bigint
language plpgsql
as $$
declare
  v_sesi_id bigint;
  v_item jsonb;
begin
  insert into public.sesi_distribusi (jenis, total_uang, total_beras, jumlah_penerima, lembaga_id, amil_pencatat)
  values (p_jenis, p_total_uang, p_total_beras, jsonb_array_length(p_items), p_lembaga_id, p_amil_pencatat)
  returning id into v_sesi_id;

  for v_item in select * from jsonb_array_elements(p_items)
  loop
    insert into public.distribusi_zakat (sesi_id, mustahik_id, jumlah_uang, jumlah_beras, lembaga_id)
    values (
      v_sesi_id,
      (v_item->>'mustahik_id')::bigint,
      coalesce((v_item->>'jumlah_uang')::numeric, 0),
      coalesce((v_item->>'jumlah_beras')::numeric, 0),
      p_lembaga_id
    );
  end loop;

  return v_sesi_id;
end;
$$;
